version: '3.8'

networks:
  microservice-network:
    driver: bridge
  app-network:
    driver: bridge
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  db-network:
    driver: bridge

volumes:
  app-data:

services:

  # App
  app-client:
    build:
      context: ./services/client
      dockerfile: Dockerfile.dev
    container_name: app-client
    volumes:
      - ./services/client/src:/usr/app/src
    tty: true
    stdin_open: true
    environment:
      PORT: "4000"
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - microservice-network
      - app-network
      - frontend-network

  app-api:
    build:
      context: ./services/api
      dockerfile: Dockerfile.dev
    container_name: app-api
    volumes:
      - ./services/api/src:/usr/app/src
    environment:
      PORT: "3000"
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - microservice-network
      - app-network
      - backend-network

  app-db:
    image: postgres:14.4
    restart: unless-stopped
    tty: true
    container_name: app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: app-db
    volumes:
      - app-data:/var/lib/postgresql/data
      - ./infrastructure/db/init:/docker-entrypoint-initdb.d/
    networks:
      - app-network
      - db-network

  # Application Gateway
  nginx-gateway:
    image: nginx:1.23.0-alpine
    container_name: nginx-gateway
    ports:
      - "8080:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservice-network

  # Tools
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - app-db
    networks:
      - microservice-network
      - app-network
      - db-network
